### ISSUE TITLE
nginx example has a fatal bug

### ISSUE THREAD

**Issue by huangyg11** [nickhammond/ansible-logrotate#10]
```
postrotate: "[ -s /run/nginx.pid ] && kill USR1 `cat /run/nginx.pid`"
```

should be 

```
postrotate: "[ -s /run/nginx.pid ] && kill -USR1 `cat /run/nginx.pid`"
```

Took me a few hours to figure out.

**Comment by nickhammond** [comment]
Good catch, thank you @huangyg11 https://github.com/nickhammond/ansible-logrotate/commit/71b0ab39066f2dfd5b2701205cf398e97cda52c2
