### ISSUE TITLE
Use GitHub releases for versioning

### ISSUE THREAD

**Issue by AMeng** [nickhammond/ansible-logrotate#13]
Would you mind using GitHub releases so that users can install a specific version? This is really useful to avoid pulling in changes from master until we decide to upgrade.

Allows you to create a `requirements.yml` like this:

``` yaml
- src: nickhammond.logrotate
  version: v1.0.0
```

**Comment by tmiller** [comment]
+1

**Comment by nickhammond** [comment]
Great idea, just added v0.0.1. I'll bump with changes.

**Comment by AMeng** [comment]
:heart:
