### ISSUE TITLE
Adding multiple paths?

### ISSUE THREAD

**Issue by pheer** [nickhammond/ansible-logrotate#22]
Is there anyway to add multiple paths to the same rotate entry?  Same for scripts (e.g. multiple scripts lines)  Does not appear to put the proper quotes.  an example would help if this is possible.  BTW thanks for putting this together...works great

**Comment by pheer** [comment]
Are the quotes needed in logrotate.d.j2 item.path ? Once I took those off I was able to add multiple paths.  thanks

**Comment by nveligeti** [comment]
we need the quotes to support the file paths with spaces but again to support multiple paths we have to treat path as a list and change the template file logrotate.d.j2 accordingly.

**Comment by pheer** [comment]
It probably should be a list, but the quotes make sense now.  Thanks

**Comment by nickhammond** [comment]
This will be supported via #26 once it's merged in.
