### ISSUE TITLE
SELinux

### ISSUE THREAD

**Issue by rgarrigue** [nickhammond/ansible-logrotate#25]
Hello

Logrotate didn't worked out of the box due to SELinux denied logrotate the access to /opt/tomcat/logs while running as daemon (meaning, interactive logrotate -v -f /etc/logrotate.conf did work, but not overnight).
Here's my resulting playbooks, maybe you should include a sefcontext in your module, or give this example in your README.md

    ---
    - hosts: all
      remote_user: root

      vars:
        logrotate_scripts:
          - name: tomcat
            path: /opt/tomcat/logs/catalina.out
            options:
              - daily
              - dateext
              - size 10M
              - rotate 30
              - missingok
              - compress
              - delaycompress
              - copytruncate

      roles:
        - nickhammond.logrotate

      tasks:
        # - debug:
        #     msg: Requires "ansible-galaxy install nickhammond.logrotate"

        # type=AVC msg=audit(1486347241.981:69221): avc:  denied  { write } for  pid=405 comm="logrotate" name="catalina.out" dev=dm-0 ino=262591 scontext=system_u:system_r:logrotate_t:s0-s0:c0.c1023 tcontext=unconfined_u:object_r:usr_t:s0 tclass=file
        # type=SYSCALL msg=audit(1486347241.981:69221): arch=c000003e syscall=2 success=no exit=-13 a0=cbec20 a1=2 a2=7fffe8ef76ef a3=746165726373662f items=0 ppid=403 pid=405 auid=0 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=9311 comm="logrotate" exe="/usr/sbin/logrotate" subj=system_u:system_r:logrotate_t:s0-s0:c0.c1023 key=(null)
        - name: Logrotate | SELinux fcontext for /opt/tomcat/logs
          # semanage fcontext -l -- | grep 'var/log'
          # semanage fcontext -l -- | grep tomcat   =>   system_u:object_r:tomcat_log_t:s0
          sefcontext:
            target: '/opt/tomcat/logs/.*?'
            seuser: system_u
            # serole: object_r # unsupported parameters
            setype: tomcat_log_t
            selevel: s0
            state: present
          # Result /opt/tomcat/logs/.*?     all files    system_u:object_r:tomcat_log_t:s0

          # # SELinux context, c/c from ls -Z /var/log/nginx/* /var/log/httpd/*
          # - name: Logrotate | SELinux context for catalina.out file
          #   file:
          #     path: /opt/tomcat/logs/catalina.out
          #     state: file
          #     selevel: s0
          #     serole: object_r
          #     seuser: system_u
          #     setype: httpd_sys_content_t

**Comment by nickhammond** [comment]
Unfortunately I don't have plans to support SELinux as this complicates the role quite a bit, thanks for the example.
