### ISSUE TITLE
Role does not provide a way to avoid duplicate entries 

### ISSUE THREAD

**Issue by colin-nolan** [nickhammond/ansible-logrotate#27]
A number of logrotate configurations come pre-defined in `/etc/logrotate.d/`. If this role is used to define the configuration for a path that is already configured, logrotate reports:
```
error: <basename(path)>:3 duplicate log entry for <path>
```
and then it looks like it gives precedence to the configuration defined in the file with the name of the lowest lowest lexicographic ordering.

It would be good if there was a way of removing any other other configurations to ensure that that set by this role gets run.

**Comment by nickhammond** [comment]
Removing files should be done with the Ansible file module with a state of absent, this role and most roles should not be destructive in their operations.
