### ISSUE TITLE
Is this module abandonware?

### ISSUE THREAD

**Issue by boldandbusted** [nickhammond/ansible-logrotate#36]
No updates since August 2016. :( 9 PRs, and 9 issues. I would be happy to help the maintainer if I can. It seems to be the most featureful implementation of logrotate in Ansible-land, but newer Ansible versions have differing ways of using roles with changed syntax and YAML-isms.

**Comment by nickhammond** [comment]
Thanks for the nudge @boldandbusted, I've updated the README and have one PR(#26) that's almost ready to merge. If you have a specific questions or issue feel free to open this back up and let me know.
