### ISSUE TITLE
Multiple Paths

### ISSUE THREAD

**Issue by IkeLutra** [nickhammond/ansible-logrotate#39]
Currently you can only pass one path to each `logrotate_scripts` element. Any issues with supporting multiple paths?

I have created a branch here: https://github.com/AgePartnership/ansible-logrotate/commit/18b94f10f32a13040353b071ab69fff9378b4fdf

Change is backwards compatible I believe.

Will setup a PR if you are happy.

I have tested on CentOS using LogRotate 3.8.6

**Comment by nickhammond** [comment]
Hey @IkeLutra, going to be merging in #26 this weekend which adds support for multiple paths while keeping backwards compatibility.

**Comment by IkeLutra** [comment]
@nickhammond Awesome thanks
