### ISSUE TITLE
logrotate_scripts from different groups conflict

### ISSUE THREAD

**Issue by oppianmatt** [nickhammond/ansible-logrotate#8]
Ok say I got a `web` group and a `db` group. The db group wants to rotate the db logs and the web group wants to rotate the web logs, and a host is in both groups.  The variable `logrotate_scripts` conflicts.

Because of how ansible works you can't define a `logrotate_scripts` in the web group vars and a different  `logrotate_scripts` in the db group vars because ansible flattens it and depending on the order the host will only ever get the one `logrotate_scripts` no matter how you select it.

**Comment by ozbillwang** [comment]
I think this role is better for your request. 

https://github.com/retr0h/ansible-logrotate

**Comment by colin-nolan** [comment]
Perhaps they weren't available at the time this issue was raised but parameterized roles now exist for solving this problem.

Suggesting that this issue is considered closed.

**Comment by oppianmatt** [comment]
@colin-nolan are the examples in https://github.com/nickhammond/ansible-logrotate/issues/9 an example of using parameterized roles?

**Comment by colin-nolan** [comment]
Yes. There's related information here: http://docs.ansible.com/ansible/playbooks_variables.html#variable-examples.

**Comment by nickhammond** [comment]
Closing in favor of the URL posted.
